
DROP DATABASE douban;
CREATE DATABASE douban;

CREATE TABLE IF NOT EXISTS douban_movies(
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL DEFAULT '',
  average VARCHAR(100) NOT NULL DEFAULT 0,
  summary VARCHAR(1024) NOT NULL DEFAULT '',
  addtime int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8